window.SONGLESS_SEEDS = [
  // ==========================================
  // RAP (90s, 2000s, 2010s, 2020s)
  // ==========================================
  // 90s classics
  { category: "rap", query: "IAM Je danse le mia" },
  { category: "rap", query: "IAM Petit frere" },
  { category: "rap", query: "IAM L empire du cote obscur" },
  { category: "rap", query: "Supreme NTM La fievre" },
  { category: "rap", query: "Supreme NTM Ma benz" },
  { category: "rap", query: "Supreme NTM Laissez passer les reves" },
  { category: "rap", query: "MC Solaar Caroline" },
  { category: "rap", query: "MC Solaar Bouge de la" },
  { category: "rap", query: "MC Solaar Solaar pleure" },
  { category: "rap", query: "Fonky Family Art de rue" },
  { category: "rap", query: "Fonky Family Sans remission" },
  // 2000s classics
  { category: "rap", query: "Sniper Gravé dans la roche" },
  { category: "rap", query: "Sniper Sans reperes" },
  { category: "rap", query: "113 tonton du bled" },
  { category: "rap", query: "113 Au singulier" },
  { category: "rap", query: "Rohff Qui est l exemple" },
  { category: "rap", query: "Rohff La puissance" },
  { category: "rap", query: "Booba Numero 10" },
  { category: "rap", query: "Booba Pitbull" },
  { category: "rap", query: "Booba Boulbi" },
  { category: "rap", query: "Sinik L assassine" },
  { category: "rap", query: "Diams La boulette" },
  { category: "rap", query: "Diams Jeune demoiselle" },
  { category: "rap", query: "Diams Confessions nocturnes" },
  { category: "rap", query: "Sefyu Molotov" },
  { category: "rap", query: "Kery James Lettre a la Republique" },
  { category: "rap", query: "Soprano A la bien" },
  { category: "rap", query: "Soprano Ferme les yeux et imagine toi" },
  // 2010s / 2020s Rap
  { category: "rap", query: "Nekfeu On verra" },
  { category: "rap", query: "Nekfeu Ma dope" },
  { category: "rap", query: "Nekfeu Tempete" },
  { category: "rap", query: "Nekfeu Elle pleut" },
  { category: "rap", query: "Orelsan Basique" },
  { category: "rap", query: "Orelsan La Terre est ronde" },
  { category: "rap", query: "Orelsan Tout va bien" },
  { category: "rap", query: "Orelsan La quete" },
  { category: "rap", query: "Ninho Jefe" },
  { category: "rap", query: "Ninho Maman ne le sait pas" },
  { category: "rap", query: "Ninho Lettre a une femme" },
  { category: "rap", query: "Ninho Goutte d eau" },
  { category: "rap", query: "PNL Au DD" },
  { category: "rap", query: "PNL Naha" },
  { category: "rap", query: "PNL Da" },
  { category: "rap", query: "PNL A l amoniaque" },
  { category: "rap", query: "SCH A7" },
  { category: "rap", query: "SCH Champs-Elysees" },
  { category: "rap", query: "SCH Fade Up" },
  { category: "rap", query: "SCH Autobahn" },
  { category: "rap", query: "Damso Macarena" },
  { category: "rap", query: "Damso Ipsite" },
  { category: "rap", query: "Damso 911" },
  { category: "rap", query: "Damso Smog" },
  { category: "rap", query: "Jul Tchikita" },
  { category: "rap", query: "Jul JC" },
  { category: "rap", query: "Jul Bande organisee" },
  { category: "rap", query: "Gazo Die" },
  { category: "rap", query: "Gazo drill fr" },
  { category: "rap", query: "PLK Mona Lisa" },
  { category: "rap", query: "PLK Problemes" },
  { category: "rap", query: "PLK Demain" },
  { category: "rap", query: "Hamza Fade Up" },
  { category: "rap", query: "Hamza Solo" },
  { category: "rap", query: "Vald Desire" },
  { category: "rap", query: "Vald Peon" },
  { category: "rap", query: "Tiakola Meuda" },
  { category: "rap", query: "Tiakola Gasolina" },
  { category: "rap", query: "SDM Bolide allemand" },
  { category: "rap", query: "SDM Mr. Ocho" },
  { category: "rap", query: "Werenoi Pyramide" },
  { category: "rap", query: "Werenoi Laboratoire" },
  { category: "rap", query: "Zola Amber" },
  { category: "rap", query: "Zola California" },
  { category: "rap", query: "Koba LaD RR 9.1" },
  { category: "rap", query: "Lomepal Yeux disent" },
  { category: "rap", query: "Lomepal Trop beau" },
  { category: "rap", query: "Lomepal Decrescendo" },

  // ==========================================
  // POP (70s, 80s, 90s, 2000s, 2010s, 2020s)
  // ==========================================
  // 70s / 80s Pop & Electro-pop
  { category: "pop", query: "Michel Polnareff Lettre a France" },
  { category: "pop", query: "Michel Polnareff Goodbye Marylou" },
  { category: "pop", query: "Indochine L aventurier" },
  { category: "pop", query: "Indochine 3eme sexe" },
  { category: "pop", query: "Indochine J ai demande a la lune" },
  { category: "pop", query: "Partenaire Particulier" },
  { category: "pop", query: "Desireless Voyage Voyage" },
  { category: "pop", query: "Jeanne Mas En rouge et noir" },
  { category: "pop", query: "Images Les demons de minuit" },
  { category: "pop", query: "Début de Soirée Nuit de folie" },
  { category: "pop", query: "Niagara L amour a la plage" },
  { category: "pop", query: "Niagara Je dois vous laisser" },
  { category: "pop", query: "Les Rita Mitsouko Marcia Baila" },
  { category: "pop", query: "Les Rita Mitsouko Andy" },
  { category: "pop", query: "Daft Punk One More Time" },
  { category: "pop", query: "Daft Punk Get Lucky" },
  // 90s / 2000s Pop
  { category: "pop", query: "Alizee Moi Lolita" },
  { category: "pop", query: "Jenifer Au soleil" },
  { category: "pop", query: "Jenifer Donne-moi le temps" },
  { category: "pop", query: "Lorie Pres de toi" },
  { category: "pop", query: "Lorie Week-end" },
  { category: "pop", query: "Kyo Derniere danse" },
  { category: "pop", query: "Kyo Le chemin" },
  { category: "pop", query: "Superbus Butterfly" },
  { category: "pop", query: "Superbus Lola" },
  { category: "pop", query: "Yelle Je veux te voir" },
  { category: "pop", query: "M Pokora Elle me controle" },
  { category: "pop", query: "Shy m Victoire" },
  { category: "pop", query: "Shy m Et alors" },
  // 2010s / 2020s Pop
  { category: "pop", query: "Stromae Papaoutai" },
  { category: "pop", query: "Stromae Formidable" },
  { category: "pop", query: "Stromae Tous les memes" },
  { category: "pop", query: "Stromae L enfer" },
  { category: "pop", query: "Angele Balance ton quoi" },
  { category: "pop", query: "Angele Tout oublier" },
  { category: "pop", query: "Angele Fever" },
  { category: "pop", query: "Angele Bruxelles je t aime" },
  { category: "pop", query: "Aya Nakamura Djadja" },
  { category: "pop", query: "Aya Nakamura Pookie" },
  { category: "pop", query: "Aya Nakamura Copines" },
  { category: "pop", query: "Clara Luciani La grenade" },
  { category: "pop", query: "Clara Luciani Respire encore" },
  { category: "pop", query: "Christine and the Queens Saint Claude" },
  { category: "pop", query: "Louane Avenir" },
  { category: "pop", query: "Louane Jour 1" },
  { category: "pop", query: "Jain Makeba" },
  { category: "pop", query: "Jain Come" },
  { category: "pop", query: "Yseult Corps" },
  { category: "pop", query: "Pomme A peu pres" },
  { category: "pop", query: "Zaho de Sagazan La symphonie des eclairs" },
  { category: "pop", query: "Pierre De Maere Un jour je marierai un ange" },
  { category: "pop", query: "Juliette Armanet Le dernier jour du disco" },
  { category: "pop", query: "Juliette Armanet Flamme" },
  { category: "pop", query: "Slimane Mon amour" },
  { category: "pop", query: "Claudio Capeo Un homme debout" },
  { category: "pop", query: "Kendji Girac Color Gitano" },
  { category: "pop", query: "Kendji Girac Andalouse" },
  { category: "pop", query: "Theodora" },
  { category: "pop", query: "Polo et Pan Canopee" },

  // ==========================================
  // VARIETE / CHANSON (70s, 80s, 90s, 2000s, 2010s)
  // ==========================================
  // 70s Variety
  { category: "variete", query: "Joe Dassin L ete indien" },
  { category: "variete", query: "Joe Dassin Les Champs-Elysees" },
  { category: "variete", query: "Joe Dassin Et si tu n existais pas" },
  { category: "variete", query: "Dalida Mourir sur scene" },
  { category: "variete", query: "Dalida Gigi l amoroso" },
  { category: "variete", query: "Dalida Paroles paroles" },
  { category: "variete", query: "Claude Francois Alexandrie Alexandra" },
  { category: "variete", query: "Claude Francois Cette annee la" },
  { category: "variete", query: "Claude Francois Le telephone pleure" },
  { category: "variete", query: "Michel Sardou Les lacs du Connemara" },
  { category: "variete", query: "Michel Sardou En chantant" },
  { category: "variete", query: "Michel Sardou La maladie d amour" },
  { category: "variete", query: "Serge Gainsbourg La Javanaise" },
  { category: "variete", query: "Serge Gainsbourg Bonnie and Clyde" },
  { category: "variete", query: "Michel Delpech Pour un flirt" },
  { category: "variete", query: "Michel Delpech Chez Laurette" },
  { category: "variete", query: "Julien Clerc Ma preference" },
  { category: "variete", query: "Michel Fugain Une belle histoire" },
  { category: "variete", query: "Maxime Le Forestier San Francisco" },
  // 80s Variety
  { category: "variete", query: "Daniel Balavoine Le chanteur" },
  { category: "variete", query: "Daniel Balavoine L aziza" },
  { category: "variete", query: "Daniel Balavoine Mon fils ma bataille" },
  { category: "variete", query: "Daniel Balavoine Tous les cris les SOS" },
  { category: "variete", query: "Michel Berger La groupie du pianiste" },
  { category: "variete", query: "Michel Berger Quelques mots d amour" },
  { category: "variete", query: "France Gall Ella elle l a" },
  { category: "variete", query: "France Gall Evidemment" },
  { category: "variete", query: "France Gall Il jouait du piano debout" },
  { category: "variete", query: "Jean-Jacques Goldman Encore un matin" },
  { category: "variete", query: "Jean-Jacques Goldman Je te donne" },
  { category: "variete", query: "Jean-Jacques Goldman Il y a" },
  { category: "variete", query: "Jean-Jacques Goldman A nos actes manques" },
  { category: "variete", query: "Renaud Mistral gagnant" },
  { category: "variete", query: "Renaud Morgane de toi" },
  { category: "variete", query: "Renaud Laisse beton" },
  { category: "variete", query: "Francis Cabrel Je l aime a mourir" },
  { category: "variete", query: "Francis Cabrel Petite Marie" },
  { category: "variete", query: "Francis Cabrel L encre de tes yeux" },
  { category: "variete", query: "Alain Souchon Foule sentimentale" },
  { category: "variete", query: "Laurent Voulzy Belle-Ile-en-Mer" },
  // 90s / 2000s Variety
  { category: "variete", query: "Celine Dion Pour que tu m aimes encore" },
  { category: "variete", query: "Celine Dion D amour ou d amitie" },
  { category: "variete", query: "Celine Dion S il suffisait d aimer" },
  { category: "variete", query: "Mylene Farmer Libertine" },
  { category: "variete", query: "Mylene Farmer Desenchantee" },
  { category: "variete", query: "Mylene Farmer Sans contrefacon" },
  { category: "variete", query: "Vanessa Paradis Joe le taxi" },
  { category: "variete", query: "Vanessa Paradis Divine Idylle" },
  { category: "variete", query: "Patrick Bruel Place des grands hommes" },
  { category: "variete", query: "Patrick Bruel Casser la voix" },
  { category: "variete", query: "Patrick Bruel Qui a le droit" },
  { category: "variete", query: "Florent Pagny Savoir aimer" },
  { category: "variete", query: "Florent Pagny Ma liberte de penser" },
  { category: "variete", query: "Pascal Obispo Lucie" },
  { category: "variete", query: "Pascal Obispo Tombé pour elle" },
  { category: "variete", query: "Garou Seul" },
  { category: "variete", query: "Garou Sous le vent" },
  { category: "variete", query: "Yannick Noah Saga Africa" },
  { category: "variete", query: "Yannick Noah La voix des sages" },
  { category: "variete", query: "Calogero En apesanteur" },
  { category: "variete", query: "Calogero Face a la mer" },
  { category: "variete", query: "Calogero Si seulement je pouvais lui manquer" },
  { category: "variete", query: "Christophe Mae On s attache" },
  { category: "variete", query: "Christophe Mae Belle demoiselle" },
  { category: "variete", query: "Zaz Je veux" },
  { category: "variete", query: "Vianney Pas la" }
];
