window.SONGLESS_SEEDS = [
  // RAP
  { category: "rap", query: "Ninho" },
  { category: "rap", query: "PNL" },
  { category: "rap", query: "SCH" },
  { category: "rap", query: "Damso" },
  { category: "rap", query: "Orelsan" },
  { category: "rap", query: "Nekfeu" },
  { category: "rap", query: "Lomepal" },
  { category: "rap", query: "Jul" },
  { category: "rap", query: "Niska" },
  { category: "rap", query: "Soprano" },
  { category: "rap", query: "Bigflo et Oli" },
  { category: "rap", query: "Dadju" },
  { category: "rap", query: "Gims" },
  { category: "rap", query: "MHD" },
  { category: "rap", query: "Tiakola" },
  { category: "rap", query: "Gazo" },
  { category: "rap", query: "PLK" },
  { category: "rap", query: "Hamza" },
  { category: "rap", query: "Koba LaD" },
  { category: "rap", query: "Franglish" },
  { category: "rap", query: "Soolking" },
  { category: "rap", query: "Booba" },
  { category: "rap", query: "Kaaris" },
  { category: "rap", query: "Vald" },
  { category: "rap", query: "SDM" },
  { category: "rap", query: "Djadja and Dinaz" },
  { category: "rap", query: "Naza" },
  { category: "rap", query: "Kendji Girac" },
  { category: "rap", query: "Maitre Gims Bella" },
  { category: "rap", query: "MHD Afro Trap" },
  { category: "rap", query: "Luidji" },
  { category: "rap", query: "Mansour" },
  { category: "rap", query: "Hatik" },
  { category: "rap", query: "Black M" },
  { category: "rap", query: "Timal" },
  { category: "rap", query: "RK" },
  { category: "rap", query: "Oboy" },
  { category: "rap", query: "Ninho Jefe" },
  { category: "rap", query: "Ninho Maman ne le sait pas" },
  { category: "rap", query: "PNL Au DD" },
  { category: "rap", query: "PNL Naha" },
  { category: "rap", query: "SCH Autobahn" },
  { category: "rap", query: "SCH Solide" },
  { category: "rap", query: "Damso Macarena" },
  { category: "rap", query: "Damso N J Respect R" },
  { category: "rap", query: "Orelsan Basique" },
  { category: "rap", query: "Orelsan La quete" },
  { category: "rap", query: "Nekfeu On verra" },
  { category: "rap", query: "Lomepal Yeux disent" },
  { category: "rap", query: "Jul Tchikita" },
  { category: "rap", query: "Jul Rien 100 rien" },

  // POP
  { category: "pop", query: "Stromae" },
  { category: "pop", query: "Angele" },
  { category: "pop", query: "Aya Nakamura" },
  { category: "pop", query: "Clara Luciani" },
  { category: "pop", query: "Christine and the Queens" },
  { category: "pop", query: "Louane" },
  { category: "pop", query: "Vianney" },
  { category: "pop", query: "Jain" },
  { category: "pop", query: "Yseult" },
  { category: "pop", query: "Pomme" },
  { category: "pop", query: "Zaho de Sagazan" },
  { category: "pop", query: "Pierre De Maere" },
  { category: "pop", query: "Juliette Armanet" },
  { category: "pop", query: "Shy m" },
  { category: "pop", query: "Alizee" },
  { category: "pop", query: "Jenifer" },
  { category: "pop", query: "M Pokora" },
  { category: "pop", query: "Kyo" },
  { category: "pop", query: "Superbus" },
  { category: "pop", query: "Kendji Girac" },
  { category: "pop", query: "Slimane" },
  { category: "pop", query: "Vitaa" },
  { category: "pop", query: "Benjamin Biolay" },
  { category: "pop", query: "Calogero" },
  { category: "pop", query: "Christophe Mae" },
  { category: "pop", query: "Black M" },
  { category: "pop", query: "Cœur de Pirate" },
  { category: "pop", query: "Amir" },
  { category: "pop", query: "Theodora" },
  { category: "pop", query: "Polo et Pan" },
  { category: "pop", query: "Stromae L enfer" },
  { category: "pop", query: "Stromae Papaoutai" },
  { category: "pop", query: "Stromae Formidable" },
  { category: "pop", query: "Angele Balance ton quoi" },
  { category: "pop", query: "Angele Tout oublier" },
  { category: "pop", query: "Aya Nakamura Djadja" },
  { category: "pop", query: "Clara Luciani La grenade" },
  { category: "pop", query: "Christine and the Queens Tilted" },
  { category: "pop", query: "Louane Avenir" },
  { category: "pop", query: "Vianney Je men vais" },
  { category: "pop", query: "Jain Makeba" },
  { category: "pop", query: "Yseult Corps" },
  { category: "pop", query: "Pomme A peu pres" },
  { category: "pop", query: "Zaho de Sagazan La symphonie des eclairs" },
  { category: "pop", query: "Pierre De Maere Un jour je marierai un ange" },
  { category: "pop", query: "Juliette Armanet Le dernier jour du disco" },
  { category: "pop", query: "Shy m Et alors" },
  { category: "pop", query: "Alizee Moi Lolita" },
  { category: "pop", query: "Jenifer Au soleil" },

  // VARIETE / CHANSON FRANCAISE
  { category: "variete", query: "Joe Dassin" },
  { category: "variete", query: "Dalida" },
  { category: "variete", query: "Claude Francois" },
  { category: "variete", query: "Michel Sardou" },
  { category: "variete", query: "Jean-Jacques Goldman" },
  { category: "variete", query: "Serge Gainsbourg" },
  { category: "variete", query: "France Gall" },
  { category: "variete", query: "Edith Piaf" },
  { category: "variete", query: "Renaud" },
  { category: "variete", query: "Daniel Balavoine" },
  { category: "variete", query: "Alain Souchon" },
  { category: "variete", query: "Michel Berger" },
  { category: "variete", query: "William Sheller" },
  { category: "variete", query: "Patrick Bruel" },
  { category: "variete", query: "Francis Cabrel" },
  { category: "variete", query: "Yannick Noah" },
  { category: "variete", query: "Pascal Obispo" },
  { category: "variete", query: "Florent Pagny" },
  { category: "variete", query: "Garou" },
  { category: "variete", query: "Enrico Macias" },
  { category: "variete", query: "Mylene Farmer" },
  { category: "variete", query: "Vanessa Paradis" },
  { category: "variete", query: "Axelle Red" },
  { category: "variete", query: "Zaz" },
  { category: "variete", query: "Julien Clerc" },
  { category: "variete", query: "Celine Dion" },
  { category: "variete", query: "Lara Fabian" },
  { category: "variete", query: "Charles Aznavour" },
  { category: "variete", query: "Johnny Hallyday" },
  { category: "variete", query: "Barbara" },
  { category: "variete", query: "Juliette Greco" },
  { category: "variete", query: "Christophe" },
  { category: "variete", query: "Mireille Mathieu" },
  { category: "variete", query: "Joe Dassin L ete indien" },
  { category: "variete", query: "Dalida Mourir sur scene" },
  { category: "variete", query: "Claude Francois Alexandrie Alexandra" },
  { category: "variete", query: "Michel Sardou Les lacs du Connemara" },
  { category: "variete", query: "Jean-Jacques Goldman Encore un matin" },
  { category: "variete", query: "Serge Gainsbourg La Javanaise" },
  { category: "variete", query: "France Gall Ella elle l a" },
  { category: "variete", query: "Edith Piaf La vie en rose" },
  { category: "variete", query: "Renaud Mistral gagnant" },
  { category: "variete", query: "Daniel Balavoine Le chanteur" },
  { category: "variete", query: "Alain Souchon Foule sentimentale" },
  { category: "variete", query: "Michel Berger La groupie du pianiste" },
  { category: "variete", query: "William Sheller Un homme heureux" },
  { category: "variete", query: "Patrick Bruel Place des grands hommes" },
  { category: "variete", query: "Francis Cabrel Je l aime a mourir" },
  { category: "variete", query: "Yannick Noah Saga Africa" },
  { category: "variete", query: "Mylene Farmer Libertine" }
];
